In [1]:
import numpy as np
import pandas as pd

In [4]:
data = np.load("C:/Users/PC/Downloads/Data_First.npz")


In [7]:
data
X_test_1 = data["X_test_1","]

In [8]:
print(X_test_1)

[[95.67 32.51  0.   ... 25.8  14.74 14.88]
 [97.63 32.31  0.   ... 27.49 14.74 14.88]
 [95.19 37.79  0.   ... 26.06 14.74 14.88]
 ...
 [96.16  0.   11.72 ... 26.39 14.76 14.89]
 [82.14  0.   10.53 ... 23.78 14.74 14.88]
 [99.06  0.    2.38 ... 29.62 14.75 14.88]]
